name: views_gallery
description: A gallery for the flash chat app views library.
version: 1.0.0
author: Jose Pereira
homepage: www.github.com/hetfdex

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  views:
    path: ../
  effective_dart: ^1.1.1

flutter:
  uses-material-design: true
