name: flash_chat_core
description: The flash chat app.
version: 1.0.0
author: Jose Pereira
homepage: www.github.com/hetfdex

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  views:
    path: ../views
  bloc: ^2.0.0
  flutter_bloc: ^2.1.1
  equatable: ^1.0.1
  firebase_auth: ^0.15.0+1
  cloud_firestore: ^0.12.10+2
  dbcrypt: ^1.0.0
  flutter_secure_storage: ^3.3.1+1
  pointycastle: ^1.0.2
  asn1lib: ^0.5.14
  effective_dart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  uses-material-design: true
  